### ISSUE TITLE
Module build failed: TypeError: template is not a function

### ISSUE THREAD

**Issue by lance032** [banderson/generator-redux#42]
ERROR in ./js/index.js
Module build failed: TypeError: template is not a function
    at exports.default (/Users/lance/git/mm-master/node_modules/babel-plugin-react-transform/lib/index.js:59:33)
    at Function.memoisePluginContainer (/Users/lance/git/mm-master/node_modules/babel-core/lib/transformation/file/plugin-manager.js:77:23)
    at PluginManager.add (/Users/lance/git/mm-master/node_modules/babel-core/lib/transformation/file/plugin-manager.js:209:30)
    at File.buildTransformers (/Users/lance/git/mm-master/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/lance/git/mm-master/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/lance/git/mm-master/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/Users/lance/git/mm-master/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/Users/lance/git/mm-master/node_modules/babel-loader/index.js:71:12)
 @ multi main

resolve: 
    "babel-plugin-react-transform": "^1.1.0",

**Comment by fidiego** [comment]
Seeing a similar issue on OS X El Capitan

```
    Asset     Size  Chunks       Chunk Names
bundle.js  59.2 kB       0       main
chunk    {0} bundle.js (main) 12.6 kB [rendered]
    [0] multi main 40 bytes {0} [built] [1 error]
    [1] ./~/querystring/decode.js 2.4 kB {0} [built]
    [2] ./~/querystring/encode.js 2.09 kB {0} [built]
    [3] ./~/querystring/index.js 127 bytes {0} [built]
    [4] (webpack)-hot-middleware/client-overlay.js 1.04 kB {0} [built]
    [5] (webpack)-hot-middleware/client.js?path=/__webpack_hmr&timeout=20000 3.35 kB {0} [built]
    [6] (webpack)-hot-middleware/~/ansi-regex/index.js 145 bytes {0} [built]
    [7] (webpack)-hot-middleware/~/strip-ansi/index.js 161 bytes {0} [built]
    [8] (webpack)-hot-middleware/process-update.js 2.95 kB {0} [built]
    [9] (webpack)/buildin/module.js 251 bytes {0} [built]

ERROR in ./js/index.js
Module build failed: TypeError: template is not a function
    at exports.default (/Users/fidiego/code/7two4/frontend/node_modules/babel-plugin-react-transform/lib/index.js:59:33)
    at Function.memoisePluginContainer (/Users/fidiego/code/7two4/frontend/node_modules/babel-core/lib/transformation/file/plugin-manager.js:77:23)
    at PluginManager.add (/Users/fidiego/code/7two4/frontend/node_modules/babel-core/lib/transformation/file/plugin-manager.js:209:30)
    at File.buildTransformers (/Users/fidiego/code/7two4/frontend/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/fidiego/code/7two4/frontend/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/fidiego/code/7two4/frontend/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/Users/fidiego/code/7two4/frontend/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/Users/fidiego/code/7two4/frontend/node_modules/babel-loader/index.js:71:12)
 @ multi main
```

**Comment by banderson** [comment]
Can you see if the latest version resolves this issues? `0.4.0`

**Comment by wangrui97** [comment]
the same question i had. finding answer
