### ISSUE TITLE
Cannot find module 'unicode/category/So'

### ISSUE THREAD

**Issue by ysm001** [banderson/generator-redux#46]
When I run `yo redux`, I get following error.

```
$ yo redux
module.js:341
    throw err;
    ^

Error: Cannot find module 'unicode/category/So'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at symbols (/usr/local/lib/node_modules/generator-redux/node_modules/slug/slug.js:6:16)
    at /usr/local/lib/node_modules/generator-redux/node_modules/slug/slug.js:199:5
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-redux/node_modules/slug/slug.js:212:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

node: v5.7.0
npm: 3.8.0
yeoman: 1.7.0

**Comment by emanuelmetal** [comment]
I have the same error on Windows 8.1.

**Comment by nalbion** [comment]
There is a pending PR which will resolve this - dodo/node-unicodetable#22
